name: Deploy Vite site to GitHub Pages

# grant the GITHUB_TOKEN the right scopes
permissions:
  contents: write      # allow pushing code
  pages: write         # allow publishing Pages
  id-token: write      # (optional, for federated auth)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # make sure the token is available
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
